import { z } from 'zod'
import { prisma } from '@/lib/prisma'
import { ok, parseBody, route } from '@/lib/api-helpers'
import {
  assertInScope,
  assertPropertyAccess,
  assertResidentAccess,
  ForbiddenError,
  requirePermission,
  restrictedPropertyIds,
  ValidationError,
} from '@/lib/tenancy'
import { generateInvoiceSchema, utilitySplitSchema } from '@/lib/validation'
import {
  appendLedger,
  applyOverdueAndLateFees,
  generateInvoice,
  generateMonthlyInvoices,
  sendRentReminders,
} from '@/server/services/billing'
import { endOfMonthUtilitySplit } from '@/server/services/residents'
import { endOfMonth, formatMoney, startOfMonth } from '@/lib/utils'

/** Catalog permission each action needs. */
const ACTION_PERMISSION = {
  GENERATE: 'rent.manage',
  REMIND: 'payments.record',
  REFRESH_OVERDUE: 'rent.manage',
  UTILITY_SPLIT: 'rent.manage',
  WAIVE: 'invoices.waive',
} as const

const schema = z.discriminatedUnion('action', [
  z.object({ action: z.literal('GENERATE') }).merge(generateInvoiceSchema),
  z.object({ action: z.literal('REMIND'), invoiceId: z.string().optional() }),
  z.object({ action: z.literal('REFRESH_OVERDUE') }),
  z.object({ action: z.literal('UTILITY_SPLIT') }).merge(utilitySplitSchema),
  z.object({
    action: z.literal('WAIVE'),
    invoiceId: z.string().min(1),
    reason: z.string().optional(),
  }),
])

/**
 * Rent operations the owner can trigger by hand — the same code the nightly
 * automation runs, so a manual run and the automatic one cannot diverge.
 */
export const POST = route(
  async ({ user, request }) => {
    const body = await parseBody(request, schema)
    requirePermission(user, ACTION_PERMISSION[body.action])
    const orgId = user.organizationId!
    // A manager limited to some PGs; null = sees every PG in the org.
    const restricted = restrictedPropertyIds(user)

    switch (body.action) {
      case 'GENERATE': {
        const month = body.month ? new Date(body.month) : new Date()
        if (body.residentId) {
          await assertResidentAccess(user, body.residentId)
          const result = await generateInvoice({
            residentId: body.residentId,
            periodStart: month,
            actor: { id: user.id, name: user.name },
            autoGenerated: false,
          })
          return ok({
            created: result.created,
            message: result.created
              ? `Invoice ${result.invoice?.number} created`
              : 'An invoice already exists for this month',
          })
        }
        const result = restricted
          ? await generateScopedInvoices(orgId, restricted, month, { id: user.id, name: user.name })
          : await generateMonthlyInvoices({
              organizationId: orgId,
              month,
              actor: { id: user.id, name: user.name },
            })
        return ok({
          ...result,
          message:
            result.created > 0
              ? `${result.created} invoices generated`
              : 'Every active resident already has an invoice for this month',
        })
      }

      case 'REMIND': {
        // The reminder run covers every PG in the org, so a manager limited
        // to some PGs cannot trigger it.
        if (restricted) {
          throw new ForbiddenError('Reminders for all PGs can only be sent by the owner')
        }
        if (body.invoiceId) {
          const invoice = await prisma.rentInvoice.findFirst({
            where: { id: body.invoiceId, organizationId: orgId },
          })
          if (!invoice) throw new ValidationError('Invoice not found')
          assertInScope(user, invoice.propertyId)
          // Reuse the scheduler by clearing today's guard for this invoice.
          await prisma.rentInvoice.update({
            where: { id: invoice.id },
            data: { lastReminderAt: null },
          })
        }
        const result = await sendRentReminders({ organizationId: orgId })
        return ok({
          sent: result.sent,
          message:
            result.sent > 0
              ? `${result.sent} reminder${result.sent === 1 ? '' : 's'} queued`
              : 'No reminders are due right now',
        })
      }

      case 'REFRESH_OVERDUE': {
        if (restricted) {
          throw new ForbiddenError('Overdue refresh runs across all PGs and is owner-only')
        }
        const result = await applyOverdueAndLateFees(orgId)
        return ok({
          ...result,
          message: `${result.flagged} invoices marked overdue, ${result.feesApplied} late fees applied`,
        })
      }

      case 'UTILITY_SPLIT': {
        await assertPropertyAccess(user, body.propertyId)
        const result = await endOfMonthUtilitySplit({
          propertyId: body.propertyId,
          month: new Date(body.month),
          totalAmount: body.totalAmount,
          kind: body.kind,
          actor: { id: user.id, name: user.name },
        })
        return ok({
          ...result,
          message: `${formatMoney(result.share)} added to ${result.residents} residents`,
        })
      }

      case 'WAIVE': {
        const invoice = await prisma.rentInvoice.findFirst({
          where: { id: body.invoiceId, organizationId: orgId },
        })
        if (!invoice) throw new ValidationError('Invoice not found')
        assertInScope(user, invoice.propertyId)
        if (!['DRAFT', 'PENDING', 'PARTIALLY_PAID', 'OVERDUE'].includes(invoice.status)) {
          throw new ValidationError('Only an unpaid invoice can be waived')
        }
        await prisma.$transaction(async (tx) => {
          await tx.rentInvoice.update({
            where: { id: invoice.id },
            data: { status: 'WAIVED', balance: 0, notes: body.reason ?? 'Waived by owner' },
          })
          await appendLedger(tx, {
            organizationId: orgId,
            residentId: invoice.residentId,
            kind: 'WAIVER',
            label: `Invoice ${invoice.number} waived`,
            credit: invoice.balance,
            refType: 'RentInvoice',
            refId: invoice.id,
          })
        })
        return ok({ message: `Invoice ${invoice.number} waived` })
      }
    }
  },
  { module: 'rent' },
)

/** generateMonthlyInvoices, limited to the PGs a restricted manager can see. */
async function generateScopedInvoices(
  organizationId: string,
  propertyIds: string[],
  monthDate: Date,
  actor: { id: string; name: string },
) {
  const month = startOfMonth(monthDate)
  const residents = await prisma.resident.findMany({
    where: {
      organizationId,
      propertyId: { in: propertyIds },
      status: { in: ['ACTIVE', 'NOTICE'] },
      joiningDate: { lte: endOfMonth(month) },
    },
    select: { id: true },
  })

  let created = 0
  let skipped = 0
  for (const resident of residents) {
    try {
      const result = await generateInvoice({ residentId: resident.id, periodStart: month, actor })
      if (result.created) created++
      else skipped++
    } catch {
      skipped++
    }
  }
  return { created, skipped, total: residents.length, month }
}
