import 'server-only'

import type {
  BedStatus,
  BillingCycle,
  DepositStatus,
  InvoiceLineKind,
  InvoiceStatus,
  PaymentMethodKind,
  Prisma,
} from '@prisma/client'
import { prisma } from '@/lib/prisma'
import { generateTempPassword, hashPassword } from '@/lib/password'
import { ConflictError, NotFoundError, ValidationError } from '@/lib/tenancy'
import { notifyOrgAdmins, notifyResident, recordActivity } from '../events'
import { sendWhatsApp } from '../integrations/whatsapp'
import { issueAuthToken } from '../auth-tokens'
import { deliverAccountLink, generatedLoginEmail, type DeliveryChannel } from './accounts'
import { assertWithinPlan } from './plan-limits'
import {
  addDays,
  daysInMonth,
  endOfMonth,
  formatDate,
  formatMoney,
  formatMonth,
  startOfDay,
  startOfMonth,
} from '@/lib/utils'
import {
  appendLedger,
  generateInvoice,
  nextCounterNumber,
  nextInvoiceNumber,
  nextReceiptNumber,
  recordPayment,
  rebuildLedger,
  retryOnUniqueConflict,
  reviseRentTx,
} from './billing'
import {
  chargeDaysInExitMonth,
  computeSettlement,
  firstDayAfterExitMonth,
  invoicesAfterExit,
  type SettlementDeduction,
} from '@/lib/settlement'
import { lineKindFor, prorationFor, rentOnDay, rentSegments } from '@/lib/billing-calc'
import { assetDeductionLabel, type AssetDamage, type Checklist } from '@/lib/checkout-checklist'

/**
 * Resident lifecycle.
 *
 * Check-in and checkout are the product's two "enter once" moments. Each runs
 * as a single transaction that updates the bed, the room/floor/PG occupancy
 * projections, the rent schedule, the deposit ledger, the food subscription,
 * the tenant login and the audit trail together — so nothing can be half-done.
 */

/**
 * RES-0001, RES-0002… from a per-organization counter. `count + 1` collided
 * after any deletion and raced between concurrent check-ins.
 */
async function nextResidentCode(tx: Prisma.TransactionClient, organizationId: string) {
  const head = 'RES-'
  return nextCounterNumber(tx, {
    key: `resident:${organizationId}`,
    head,
    taken: async (code) =>
      Boolean(
        await tx.resident.findUnique({
          where: { organizationId_code: { organizationId, code } },
          select: { id: true },
        }),
      ),
    used: async () =>
      (
        await tx.resident.findMany({
          where: { organizationId, code: { startsWith: head } },
          select: { code: true },
        })
      ).map((r) => r.code),
  })
}

/** Bed states a new occupant may move into (RESERVED is held for them). */
const CLAIMABLE_BED_STATUSES: BedStatus[] = ['AVAILABLE', 'RESERVED']

export type CheckInInput = {
  organizationId: string
  propertyId: string
  bedId: string

  fullName: string
  phone: string
  whatsappPhone?: string
  email?: string
  photoUrl?: string
  dateOfBirth?: Date | null
  gender?: string
  bloodGroup?: string
  qualification?: string
  permanentAddress?: string
  city?: string
  state?: string
  pincode?: string

  guardianName?: string
  guardianRelation?: string
  guardianPhone?: string
  guardianAddress?: string

  occupationType?: string
  companyName?: string
  companyAddress?: string
  designation?: string

  idType?: string
  idNumber?: string

  joiningDate: Date
  rentAmount: number
  depositAmount: number
  maintenanceFee?: number
  foodOptIn?: boolean
  foodCharge?: number
  foodPlanId?: string | null
  billingCycle?: BillingCycle
  rentDueDay?: number
  discountAmount?: number
  discountNote?: string
  notes?: string
  signatureUrl?: string

  /** Collect the deposit as part of check-in. */
  depositCollected?: boolean
  /** Create a tenant login and send them an invite link to set a password. */
  createTenantAccount?: boolean
  /** Resident agreed to rent reminders and updates on WhatsApp. */
  whatsappConsent?: boolean

  documents?: { kind: string; label: string; fileUrl: string }[]

  /** Converting a booking: its RESERVED bed is accepted and its token becomes the first payment. */
  bookingId?: string

  actor: { id?: string; name: string }
}

export async function checkInResident(input: CheckInInput) {
  if (input.rentAmount <= 0) throw new ValidationError('Rent must be greater than zero')
  await assertWithinPlan(input.organizationId, 'residents')

  // A clash on the resident code or receipt number re-runs the whole check-in.
  const result = await retryOnUniqueConflict(() => checkInOnce(input), ['code', 'receiptNumber'])

  // --- Post-commit: first invoice + welcome message ------------------------
  // The resident is checked in either way, but a missing first invoice is
  // lost rent: log it and tell the caller instead of swallowing it.
  let firstInvoiceError = null as string | null
  const first = await generateInvoice({
    residentId: result.resident.id,
    periodStart: startOfMonth(result.resident.joiningDate),
    actor: input.actor,
    autoGenerated: true,
  }).catch((error: unknown) => {
    firstInvoiceError = error instanceof Error ? error.message : String(error)
    console.error('[residents] first invoice failed after check-in', {
      organizationId: input.organizationId,
      residentId: result.resident.id,
      error,
    })
    return { invoice: null, created: false }
  })

  // A booking token becomes the first rent payment, allocated to the first
  // invoice (or held as advance if that invoice could not be raised).
  let tokenPayment = null as { receiptNumber: string; amount: number } | null
  let tokenPaymentError = null as string | null
  const booking = result.booking
  if (booking && booking.tokenAmount > 0 && booking.tokenPaidAt) {
    const method = ['CASH', 'UPI', 'BANK_TRANSFER', 'CARD', 'CHEQUE'].includes(booking.tokenMethod ?? '')
      ? (booking.tokenMethod as 'CASH' | 'UPI' | 'BANK_TRANSFER' | 'CARD' | 'CHEQUE')
      : 'CASH'
    try {
      const paid = await recordPayment({
        residentId: result.resident.id,
        amount: booking.tokenAmount,
        method,
        paidAt: booking.tokenPaidAt,
        reference: booking.tokenReference ?? undefined,
        notes: `Booking token (${booking.code})`,
        invoiceIds: first.invoice ? [first.invoice.id] : undefined,
        actor: input.actor,
      })
      tokenPayment = { receiptNumber: paid.payment.receiptNumber, amount: paid.payment.amount }
    } catch (error) {
      tokenPaymentError = error instanceof Error ? error.message : String(error)
      console.error('[residents] booking token payment failed after check-in', {
        residentId: result.resident.id,
        bookingId: booking.id,
        error,
      })
    }
  }

  await notifyResident(result.resident.id, {
    organizationId: input.organizationId,
    kind: 'SYSTEM',
    title: `Welcome to ${result.property.name}`,
    body: `Your room is ${result.bed.room.number}, bed ${result.bed.label}. Rent ${formatMoney(result.resident.rentAmount)} per month.`,
    link: '/tenant',
  })

  // WhatsApp only with the resident's consent (recorded at check-in).
  const whatsappAllowed = Boolean(result.resident.whatsappConsentAt)
  const whatsappTo = result.resident.whatsappPhone || result.resident.phone
  if (whatsappAllowed) {
    await sendWhatsApp({
      organizationId: input.organizationId,
      toName: result.resident.fullName,
      toPhone: whatsappTo,
      template: 'welcome_resident',
      body:
        `Hi ${result.resident.fullName.split(' ')[0]} 👋\n\n` +
        `Welcome to ${result.property.name}!\n\n` +
        `Room: ${result.bed.room.number} · Bed ${result.bed.label}\n` +
        `Rent: ${formatMoney(result.resident.rentAmount)} / month\n` +
        `Joining date: ${formatDate(result.resident.joiningDate)}\n\n` +
        (result.tenantUserId
          ? `We're sending you a separate link to set your resident app password.\n\n`
          : '') +
        `You can pay rent, raise complaints and see the food menu from the app.`,
      variables: [
        result.resident.fullName,
        result.property.name,
        `${result.bed.room.number} / ${result.bed.label}`,
      ],
      refType: 'Resident',
      refId: result.resident.id,
    }).catch(() => undefined)
  }

  // The resident app login is handed over as a single-use invite link, never
  // a password. The owner also gets the link to share by hand.
  let inviteUrl: string | null = null
  let inviteSentVia: DeliveryChannel[] = []
  if (result.tenantUserId && result.tenantEmail) {
    try {
      const { url } = await issueAuthToken(result.tenantUserId, 'INVITE')
      inviteUrl = url
      inviteSentVia = await deliverAccountLink({
        kind: 'INVITE',
        url,
        recipient: {
          id: result.tenantUserId,
          name: result.resident.fullName,
          email: result.tenantEmail,
          phone: whatsappTo,
        },
        organizationId: input.organizationId,
        orgName: result.property.name,
        whatsapp: whatsappAllowed,
      })
    } catch (error) {
      console.error('[residents] invite after check-in failed', {
        residentId: result.resident.id,
        error,
      })
    }
  }

  return {
    ...result,
    firstInvoice: first.invoice,
    firstInvoiceError,
    inviteUrl,
    inviteSentVia,
    tokenPayment,
    tokenPaymentError,
  }
}

async function checkInOnce(input: CheckInInput) {
  return prisma.$transaction(
    async (tx) => {
      const property = await tx.property.findFirst({
        where: { id: input.propertyId, organizationId: input.organizationId, archivedAt: null },
        include: { organization: { include: { settings: true } } },
      })
      if (!property) throw new NotFoundError('PG not found')

      // Friendly checks first; the atomic claim below is what actually
      // prevents two check-ins from taking the same bed.
      const bed = await tx.bed.findFirst({
        where: { id: input.bedId, propertyId: property.id },
        include: { room: true, floor: true },
      })
      if (!bed) throw new NotFoundError('Bed not found in this PG')
      if (bed.status === 'OCCUPIED' || bed.residentId) {
        throw new ConflictError('This bed is already occupied')
      }
      if (bed.status === 'MAINTENANCE' || bed.status === 'BLOCKED') {
        throw new ConflictError(`This bed is marked ${bed.status.toLowerCase()}`)
      }

      // --- Booking conversion ---------------------------------------------
      // A bed held by a live booking may only be taken by that booking.
      const booking = input.bookingId
        ? await tx.booking.findFirst({
            where: { id: input.bookingId, organizationId: input.organizationId, propertyId: property.id },
          })
        : null
      if (input.bookingId && !booking) throw new NotFoundError('Booking not found in this PG')
      if (booking && booking.status !== 'PENDING' && booking.status !== 'CONFIRMED') {
        throw new ConflictError(`Booking ${booking.code} is ${booking.status.toLowerCase().replace('_', ' ')}`)
      }
      if (bed.status === 'RESERVED') {
        const holder = await tx.booking.findFirst({
          where: { bedId: bed.id, status: 'CONFIRMED' },
          select: { id: true, code: true, name: true },
        })
        if (holder && holder.id !== booking?.id) {
          throw new ConflictError(`This bed is reserved for ${holder.name} (${holder.code})`)
        }
      }

      const code = await nextResidentCode(tx, input.organizationId)
      const joiningDate = startOfDay(input.joiningDate)

      const resident = await tx.resident.create({
        data: {
          organizationId: input.organizationId,
          propertyId: property.id,
          roomId: bed.roomId,
          code,
          fullName: input.fullName.trim(),
          phone: input.phone.trim(),
          whatsappPhone: input.whatsappPhone?.trim() || input.phone.trim(),
          whatsappConsentAt: input.whatsappConsent === false ? null : new Date(),
          email: input.email?.trim() || null,
          photoUrl: input.photoUrl,
          dateOfBirth: input.dateOfBirth ?? null,
          gender: input.gender ?? (property.type === 'MENS' ? 'MALE' : property.type === 'WOMENS' ? 'FEMALE' : null),
          bloodGroup: input.bloodGroup,
          qualification: input.qualification,
          permanentAddress: input.permanentAddress,
          city: input.city,
          state: input.state,
          pincode: input.pincode,
          guardianName: input.guardianName,
          guardianRelation: input.guardianRelation,
          guardianPhone: input.guardianPhone,
          guardianAddress: input.guardianAddress,
          occupationType: input.occupationType,
          companyName: input.companyName,
          companyAddress: input.companyAddress,
          designation: input.designation,
          idType: input.idType,
          idNumber: input.idNumber,
          kycStatus: input.idNumber ? 'PENDING' : 'NOT_SUBMITTED',
          status: 'ACTIVE',
          joiningDate,
          rentAmount: input.rentAmount,
          depositAmount: input.depositAmount,
          maintenanceFee: input.maintenanceFee ?? 0,
          foodOptIn: input.foodOptIn ?? true,
          foodCharge: input.foodCharge ?? 0,
          billingCycle: input.billingCycle ?? 'MONTHLY',
          rentDueDay: input.rentDueDay ?? property.organization.settings?.rentDueDay ?? 5,
          discountAmount: input.discountAmount ?? 0,
          discountNote: input.discountNote,
          notes: input.notes,
          signatureUrl: input.signatureUrl,
          documents: input.documents?.length
            ? {
                create: input.documents.map((d) => ({
                  kind: d.kind as never,
                  label: d.label,
                  fileUrl: d.fileUrl,
                })),
              }
            : undefined,
        },
      })

      // --- Bed becomes occupied; allocation history starts -----------------
      // Conditional claim: a concurrent check-in blocks on the row, then sees
      // it taken and matches nothing.
      const claim = await tx.bed.updateMany({
        where: { id: bed.id, residentId: null, status: { in: CLAIMABLE_BED_STATUSES } },
        data: { status: 'OCCUPIED', residentId: resident.id },
      })
      if (claim.count !== 1) throw new ConflictError('That bed was just taken — pick another')
      await tx.bedAllocation.create({
        data: { bedId: bed.id, residentId: resident.id, fromDate: joiningDate },
      })

      if (booking) {
        // They moved into a different bed than the one held: free the old one.
        if (booking.status === 'CONFIRMED' && booking.bedId && booking.bedId !== bed.id) {
          await tx.bed.updateMany({
            where: { id: booking.bedId, status: 'RESERVED', residentId: null },
            data: { status: 'AVAILABLE' },
          })
        }
        await tx.booking.update({
          where: { id: booking.id },
          data: { status: 'CHECKED_IN', residentId: resident.id, bedId: bed.id },
        })
        if (booking.leadId) {
          const lead = await tx.residentLead.findUnique({
            where: { id: booking.leadId },
            select: { id: true, status: true, residentId: true },
          })
          if (lead && !lead.residentId) {
            await tx.residentLead.update({
              where: { id: lead.id },
              data: { status: 'CHECKED_IN', residentId: resident.id, nextFollowUpAt: null, lostReason: null },
            })
            await tx.residentLeadActivity.create({
              data: {
                leadId: lead.id,
                kind: 'STATUS',
                body: `Checked in as ${code} · Room ${bed.room.number}, Bed ${bed.label} (booking ${booking.code})`,
                actorName: input.actor.name,
              },
            })
          }
        }
      }

      // --- Security deposit ledger ----------------------------------------
      const deposit = await tx.securityDeposit.create({
        data: {
          organizationId: input.organizationId,
          residentId: resident.id,
          amount: input.depositAmount,
          collected: input.depositCollected ? input.depositAmount : 0,
          status: input.depositCollected ? 'COLLECTED' : 'PENDING',
          collectedAt: input.depositCollected ? new Date() : null,
        },
      })

      if (input.depositCollected && input.depositAmount > 0) {
        const receiptNumber = await nextReceiptNumber(
          tx,
          input.organizationId,
          property.organization.settings?.receiptPrefix ?? 'RCP',
          new Date(),
        )
        await tx.rentPayment.create({
          data: {
            organizationId: input.organizationId,
            propertyId: property.id,
            residentId: resident.id,
            receiptNumber,
            amount: input.depositAmount,
            method: 'CASH',
            // Held money, not rent: never allocated to invoices or counted as revenue.
            purpose: 'DEPOSIT',
            status: 'SUCCESS',
            notes: 'Security deposit collected at check-in',
            recordedBy: input.actor.name,
          },
        })
        await appendLedger(tx, {
          organizationId: input.organizationId,
          residentId: resident.id,
          kind: 'DEPOSIT',
          label: `Security deposit received (${receiptNumber})`,
          entryDate: joiningDate,
          refType: 'SecurityDeposit',
          refId: deposit.id,
        })
      }

      // --- Food subscription ----------------------------------------------
      if (input.foodOptIn !== false) {
        const plan = input.foodPlanId
          ? await tx.foodPlan.findFirst({
              where: { id: input.foodPlanId, propertyId: property.id },
            })
          : await tx.foodPlan.findFirst({
              where: { propertyId: property.id, active: true },
              orderBy: [{ isDefault: 'desc' }, { createdAt: 'asc' }],
            })
        if (plan) {
          await tx.foodSubscription.create({
            data: {
              residentId: resident.id,
              foodPlanId: plan.id,
              startDate: joiningDate,
              active: true,
            },
          })
        }
      }

      // --- Tenant login ----------------------------------------------------
      let tenantEmail: string | null = null
      let tenantUserId: string | null = null
      if (input.createTenantAccount !== false) {
        const generated = generatedLoginEmail(code, property.organization.slug)
        const base = input.email?.trim().toLowerCase() || generated
        const exists = await tx.user.findUnique({ where: { email: base } })
        tenantEmail = exists ? generated : base

        // Unusable random password: the resident sets their own from the
        // invite link sent after the transaction commits.
        const user = await tx.user.create({
          data: {
            organizationId: input.organizationId,
            email: tenantEmail,
            phone: resident.phone,
            name: resident.fullName,
            passwordHash: await hashPassword(generateTempPassword(32)),
            role: 'TENANT',
            status: 'ACTIVE',
            mustChangePassword: true,
            avatarUrl: input.photoUrl,
          },
        })
        await tx.resident.update({ where: { id: resident.id }, data: { userId: user.id } })
        tenantUserId = user.id
      }

      // --- Audit + notifications -------------------------------------------
      await recordActivity(
        {
          organizationId: input.organizationId,
          propertyId: property.id,
          actorId: input.actor.id,
          actorName: input.actor.name,
          event: 'RESIDENT_CHECKED_IN',
          entityType: 'Resident',
          entityId: resident.id,
          summary: `${resident.fullName} checked into ${property.name} · Room ${bed.room.number} · Bed ${bed.label}`,
          meta: {
            residentCode: code,
            room: bed.room.number,
            bed: bed.label,
            rent: input.rentAmount,
            deposit: input.depositAmount,
          },
        },
        tx,
      )
      await recordActivity(
        {
          organizationId: input.organizationId,
          propertyId: property.id,
          actorId: input.actor.id,
          actorName: input.actor.name,
          event: 'BED_ALLOCATED',
          entityType: 'Bed',
          entityId: bed.id,
          summary: `Bed ${bed.label} in Room ${bed.room.number} allocated to ${resident.fullName}`,
        },
        tx,
      )
      await notifyOrgAdmins(
        input.organizationId,
        {
          kind: 'SYSTEM',
          title: 'New resident checked in',
          body: `${resident.fullName} — ${property.name}, Room ${bed.room.number}, Bed ${bed.label}.`,
          link: `/app/residents/${resident.id}`,
        },
        tx,
      )

      return { resident, bed, property, deposit, tenantEmail, tenantUserId, booking }
    },
    { timeout: 20000 },
  )
}

// --------------------------------------------------------------------------
// Room / bed transfer
// --------------------------------------------------------------------------

export async function transferResident(params: {
  residentId: string
  toBedId: string
  actor: { id?: string; name: string }
  effectiveDate?: Date
  /**
   * New monthly rent from the transfer date (a RentRevision). Months already
   * invoiced get a pro-rata debit or credit note for the difference.
   */
  newRent?: number
  rentReason?: string
}) {
  return prisma.$transaction(async (tx) => {
    const resident = await tx.resident.findUnique({
      where: { id: params.residentId },
      include: { bed: { include: { room: true } }, property: true },
    })
    if (!resident) throw new NotFoundError('Resident not found')
    if (resident.status === 'CHECKED_OUT') throw new ConflictError('Resident has checked out')

    const target = await tx.bed.findFirst({
      where: { id: params.toBedId, propertyId: resident.propertyId },
      include: { room: true },
    })
    if (!target) throw new NotFoundError('Target bed not found in this PG')
    if (resident.bed?.id === target.id) throw new ValidationError('They are already in this bed')
    if (target.residentId && target.residentId !== resident.id) {
      throw new ConflictError('This bed is already occupied')
    }
    if (target.status === 'MAINTENANCE' || target.status === 'BLOCKED') {
      throw new ConflictError(`This bed is marked ${target.status.toLowerCase()}`)
    }

    const date = startOfDay(params.effectiveDate ?? new Date())

    if (resident.bed) {
      await tx.bed.update({
        where: { id: resident.bed.id },
        data: { status: 'AVAILABLE', residentId: null },
      })
      await tx.bedAllocation.updateMany({
        where: { bedId: resident.bed.id, residentId: resident.id, toDate: null },
        data: { toDate: date },
      })
    }

    // Atomic claim (after releasing the old bed, so moving back onto the same
    // bed still works): a concurrent check-in or transfer cannot also win it.
    const claim = await tx.bed.updateMany({
      where: { id: target.id, residentId: null, status: { in: CLAIMABLE_BED_STATUSES } },
      data: { status: 'OCCUPIED', residentId: resident.id },
    })
    if (claim.count !== 1) throw new ConflictError('That bed was just taken — pick another')
    await tx.bedAllocation.create({
      data: { bedId: target.id, residentId: resident.id, fromDate: date },
    })
    await tx.resident.update({ where: { id: resident.id }, data: { roomId: target.roomId } })

    const from = resident.bed ? `Room ${resident.bed.room.number} / Bed ${resident.bed.label}` : 'unallocated'
    const to = `Room ${target.room.number} / Bed ${target.label}`

    // Rent difference: a revision from the transfer date. reviseRentTx raises
    // the debit/credit notes for months already invoiced and audits itself.
    const revisions = await tx.rentRevision.findMany({
      where: { residentId: resident.id },
      select: { oldRent: true, newRent: true, effectiveFrom: true },
    })
    const rentBefore = rentOnDay(date, resident.rentAmount, revisions)
    let rentChange: Awaited<ReturnType<typeof reviseRentTx>> | null = null
    if (params.newRent != null && params.newRent !== resident.rentAmount) {
      rentChange = await reviseRentTx(tx, {
        organizationId: resident.organizationId,
        residentId: resident.id,
        newRent: params.newRent,
        effectiveFrom: date,
        reason: params.rentReason?.trim() || `Moved to ${to}`,
        actor: params.actor,
      })
    }

    await recordActivity(
      {
        organizationId: resident.organizationId,
        propertyId: resident.propertyId,
        actorId: params.actor.id,
        actorName: params.actor.name,
        event: 'ROOM_CHANGED',
        entityType: 'Resident',
        entityId: resident.id,
        summary: `${resident.fullName} moved from ${from} to ${to}${
          rentChange ? ` — rent ${formatMoney(rentBefore)} → ${formatMoney(params.newRent!)} from ${formatDate(date)}` : ''
        }`,
        before: { bedId: resident.bed?.id ?? null, bed: from, rentAmount: resident.rentAmount },
        after: { bedId: target.id, bed: to, rentAmount: params.newRent ?? resident.rentAmount, effectiveDate: date.toISOString() },
        meta: rentChange ? { revisionId: rentChange.revision.id, adjustments: rentChange.adjustments } : undefined,
      },
      tx,
    )
    await notifyResident(
      resident.id,
      {
        organizationId: resident.organizationId,
        kind: 'SYSTEM',
        title: 'Your room has changed',
        body: `You are now in Room ${target.room.number}, Bed ${target.label}.`,
        link: '/tenant',
      },
      tx,
    )

    return { resident, bed: target, rentChange }
  })
}

// --------------------------------------------------------------------------
// Checkout
// --------------------------------------------------------------------------

type Db = Prisma.TransactionClient | typeof prisma

const OPEN_INVOICE: InvoiceStatus[] = ['PENDING', 'PARTIALLY_PAID', 'OVERDUE']

export type RefundInput = {
  method: string
  reference?: string
  note?: string
  paidAt?: Date
}

export type CheckoutPreview = {
  residentId: string
  residentName: string
  exitDate: Date
  joiningDate: Date
  noticeDate: Date | null
  plannedExitDate: Date | null
  openInvoices: { id: string; number: string; balance: number; dueDate: Date }[]
  outstandingRent: number
  utilities: { id: string; label: string; amount: number }[]
  utilityCharges: number
  deductions: SettlementDeduction[]
  deductionsTotal: number
  exitMonth: {
    label: string
    invoiced: boolean
    usedDays: number
    unusedDays: number
    charge: number
    credit: number
    lines: { label: string; amount: number }[]
  }
  /** One-time charges (joining, notice, fines) not billed yet — on the settlement. */
  oneTimeCharges: { label: string; amount: number }[]
  oneTimeTotal: number
  /** Invoices for months after the exit; cancelled at checkout. */
  futureInvoices: { id: string; number: string; period: string; total: number; amountPaid: number }[]
  /** Assets in the resident's room or bed, for the damage / missing check. */
  roomAssets: {
    id: string
    name: string
    category: string
    condition: string
    status: string
    value: number
  }[]
  depositHeld: number
  depositStatus: string | null
  advance: number
  owed: number
  credits: number
  applied: { unusedCredit: number; advance: number; deposit: number }
  refundable: number
  payable: number
  /** Kept for older callers. */
  suggestedRefund: number
  suggestedPayable: number
}

function exitLineLabel(kind: string, from: Date, exit: Date, used: number, total: number) {
  const span = `${formatDate(from)} – ${formatDate(exit)} (${used}/${total} days)`
  switch (kind) {
    case 'RENT':
      return `Room rent ${span}`
    case 'MAINTENANCE':
      return `Maintenance ${span}`
    case 'FOOD':
      return `Food plan ${span}`
    default:
      return `Discount ${span}`
  }
}

/** Invoice line kind for an exit-month line. */
function exitLineKind(l: { kind: string; category?: string }): InvoiceLineKind {
  if (l.kind === 'CHARGE') return lineKindFor(l.category ?? 'OTHER')
  return l.kind as InvoiceLineKind
}

/**
 * Reads everything the settlement depends on through `db` — the plain client
 * for the preview, the checkout's own transaction for the real thing — and
 * runs the pure arithmetic over it.
 *
 * Covers: open invoices up to the exit month, invoices for later months
 * (cancelled; money paid on them comes back as advance), unbilled utilities,
 * unbilled one-time charges, the exit month pro-rata with rent revisions and
 * recurring charges/discounts, asset damage, deposit and advance.
 */
async function loadSettlement(
  db: Db,
  params: {
    residentId: string
    exitDate: Date
    deductions: SettlementDeduction[]
    assetDamages?: AssetDamage[]
  },
) {
  const exitDate = startOfDay(params.exitDate)
  const nextMonth = firstDayAfterExitMonth(exitDate)
  const resident = await db.resident.findUnique({
    where: { id: params.residentId },
    include: {
      deposit: true,
      bed: { select: { id: true, label: true, roomId: true } },
      invoices: {
        where: { status: { in: OPEN_INVOICE }, balance: { gt: 0 }, periodStart: { lt: nextMonth } },
        orderBy: { dueDate: 'asc' },
      },
      utilityCharges: { where: { billed: false }, orderBy: { periodStart: 'asc' } },
      payments: {
        where: { status: 'SUCCESS' },
        orderBy: [{ paidAt: 'asc' }, { createdAt: 'asc' }],
        select: {
          id: true,
          amount: true,
          refundedAmount: true,
          purpose: true,
          allocations: { select: { amount: true, invoiceId: true } },
        },
      },
      charges: { where: { voidedAt: null } },
      rentRevisions: { select: { oldRent: true, newRent: true, effectiveFrom: true } },
    },
  })
  if (!resident) throw new NotFoundError('Resident not found')

  const joining = startOfDay(new Date(resident.joiningDate))
  if (exitDate < joining) {
    throw new ValidationError(`The exit date cannot be before the joining date (${formatDate(joining)}).`)
  }

  // --- Invoices for months after the exit: cancelled at checkout -----------
  const futureInvoices = invoicesAfterExit(
    await db.rentInvoice.findMany({
      where: { residentId: resident.id, periodStart: { gte: nextMonth }, status: { notIn: ['CANCELLED', 'WAIVED'] } },
      select: { id: true, number: true, periodStart: true, issueDate: true, total: true, amountPaid: true, status: true },
      orderBy: { periodStart: 'asc' },
    }),
    exitDate,
  )
  const futureIds = new Set(futureInvoices.map((i) => i.id))

  // --- Exit month: pro-rata charge, or credit for days already billed -------
  const monthStart = startOfMonth(exitDate)
  const totalDays = daysInMonth(monthStart)
  const fromDate = joining > monthStart ? joining : monthStart
  const exitMonthInvoice = await db.rentInvoice.findUnique({
    where: { residentId_periodStart: { residentId: resident.id, periodStart: monthStart } },
    include: { lines: true },
  })
  let invoicedCharge: number | null = null
  if (exitMonthInvoice) {
    invoicedCharge =
      exitMonthInvoice.status === 'WAIVED' || exitMonthInvoice.status === 'CANCELLED'
        ? 0
        : Math.max(
            0,
            exitMonthInvoice.lines
              .filter((l) => l.kind === 'RENT' || l.kind === 'MAINTENANCE' || l.kind === 'FOOD' || l.kind === 'LAUNDRY')
              .reduce((s, l) => s + l.amount, 0) - exitMonthInvoice.discount,
          )
  }

  // Rent by day (a revision can change it inside the month).
  const proration = prorationFor(resident.joiningDate, monthStart, startOfDay(endOfMonth(monthStart)))
  const segments = rentSegments(monthStart, proration, resident.rentAmount, resident.rentRevisions).map(
    ({ fromDay, toDay, monthlyRent }) => ({ fromDay, toDay, monthlyRent }),
  )

  // Recurring charges and discounts active in the exit month.
  const recurring = resident.charges
    .filter((c) => c.kind !== 'ONE_TIME' && c.amount > 0)
    .flatMap((c) => {
      const days = chargeDaysInExitMonth(c, exitDate)
      return days
        ? [{ label: c.label, category: c.category, amount: c.amount, discount: c.kind === 'DISCOUNT', ...days }]
        : []
    })

  // One-time charges not billed yet (or billed on an invoice being cancelled).
  const oneTime = resident.charges.filter(
    (c) => c.kind === 'ONE_TIME' && c.amount > 0 && (!c.billedInvoiceId || futureIds.has(c.billedInvoiceId)),
  )

  // --- Money held: unallocated rent advance and deposit payments ------------
  // Allocations to invoices being cancelled are released, so they count as free.
  const free = (p: (typeof resident.payments)[number]) =>
    Math.max(
      0,
      p.amount -
        p.refundedAmount -
        p.allocations.filter((a) => !futureIds.has(a.invoiceId)).reduce((s, a) => s + a.amount, 0),
    )
  const rentPayments = resident.payments
    .filter((p) => p.purpose === 'RENT')
    .map((p) => ({ id: p.id, free: free(p) }))
    .filter((p) => p.free > 0)
  const depositPayments = resident.payments
    .filter((p) => p.purpose === 'DEPOSIT')
    .map((p) => ({ id: p.id, free: free(p) }))
    .filter((p) => p.free > 0)
  const advance = rentPayments.reduce((s, p) => s + p.free, 0)
  const depositHeld = Math.max(0, (resident.deposit?.collected ?? 0) - (resident.deposit?.deductions ?? 0) - (resident.deposit?.refunded ?? 0))

  const openBalances = resident.invoices.reduce((s, i) => s + i.balance, 0)
  const utilities = resident.utilityCharges.map((u) => ({
    id: u.id,
    kind: u.kind,
    label: `${u.kind.charAt(0)}${u.kind.slice(1).toLowerCase()} — ${formatMonth(u.periodStart)}${
      u.unitsUsed ? ` (${u.unitsUsed} units)` : ''
    }`,
    amount: u.amount,
  }))

  // --- Assets in the room or bed: damage and missing items -----------------
  const roomId = resident.bed?.roomId ?? resident.roomId
  const roomAssets = await db.asset.findMany({
    where: {
      organizationId: resident.organizationId,
      propertyId: resident.propertyId,
      status: { notIn: ['DISPOSED', 'MISSING'] },
      OR: [...(resident.bed ? [{ bedId: resident.bed.id }] : []), ...(roomId ? [{ roomId }] : [])],
    },
    orderBy: [{ category: 'asc' }, { name: 'asc' }],
  })
  const damages = dedupeDamages(params.assetDamages ?? [])
  const assetDeductions: SettlementDeduction[] = []
  const damagedAssets: { asset: (typeof roomAssets)[number]; damage: AssetDamage }[] = []
  if (damages.length) {
    if (!roomAssets.length && (resident.bed || roomId)) {
      throw new ValidationError('No assets are recorded in this room or bed')
    }
    for (const damage of damages) {
      const asset = roomAssets.find((a) => a.id === damage.assetId)
      if (!asset) throw new ValidationError('That item is not in this resident\'s room or bed')
      damagedAssets.push({ asset, damage })
      assetDeductions.push({
        label: assetDeductionLabel(asset.name, damage.outcome, damage.note),
        amount: damage.amount,
      })
    }
  }

  const result = computeSettlement({
    openBalances,
    utilities: utilities.reduce((s, u) => s + u.amount, 0),
    deductions: [...params.deductions, ...assetDeductions],
    exitMonth: {
      totalDays,
      fromDay: fromDate.getDate(),
      exitDay: exitDate.getDate(),
      monthly: {
        rent: resident.rentAmount,
        maintenance: resident.maintenanceFee,
        food: resident.foodOptIn ? resident.foodCharge : 0,
        discount: resident.discountAmount,
      },
      rentSegments: segments,
      recurring,
      invoicedCharge,
    },
    oneTimeCharges: oneTime.map((c) => ({ label: c.label, category: c.category, amount: c.amount })),
    depositCollected: depositHeld,
    advance,
  })

  const span = (used: number) => `${formatDate(fromDate)} – ${formatDate(exitDate)} (${used}/${totalDays} days)`
  const exitLines = result.exitMonthLines.map((l) => ({
    kind: exitLineKind(l),
    label: l.label ? `${l.label} ${span(result.usedDays)}` : exitLineLabel(l.kind, fromDate, exitDate, result.usedDays, totalDays),
    amount: l.amount,
  }))

  return {
    resident,
    exitDate,
    monthStart,
    totalDays,
    exitMonthInvoice,
    futureInvoices,
    oneTimeIds: oneTime.map((c) => c.id),
    roomAssets,
    damagedAssets,
    rentPayments,
    depositPayments,
    depositHeld,
    advance,
    utilities,
    exitLines,
    result,
  }
}

/** One entry per asset; the last one wins. */
function dedupeDamages(list: AssetDamage[]) {
  const byId = new Map<string, AssetDamage>()
  for (const d of list) byId.set(d.assetId, d)
  return [...byId.values()]
}

type LoadedSettlement = Awaited<ReturnType<typeof loadSettlement>>

function toPreview(s: LoadedSettlement): CheckoutPreview {
  const r = s.result
  return {
    residentId: s.resident.id,
    residentName: s.resident.fullName,
    exitDate: s.exitDate,
    joiningDate: s.resident.joiningDate,
    noticeDate: s.resident.noticeDate,
    plannedExitDate: s.resident.exitDate,
    openInvoices: s.resident.invoices.map((i) => ({
      id: i.id,
      number: i.number,
      balance: i.balance,
      dueDate: i.dueDate,
    })),
    outstandingRent: s.resident.invoices.reduce((sum, i) => sum + i.balance, 0),
    utilities: s.utilities.map(({ id, label, amount }) => ({ id, label, amount })),
    utilityCharges: s.utilities.reduce((sum, u) => sum + u.amount, 0),
    deductions: r.deductions,
    deductionsTotal: r.deductionsTotal,
    exitMonth: {
      label: formatMonth(s.monthStart),
      invoiced: Boolean(s.exitMonthInvoice),
      usedDays: r.usedDays,
      unusedDays: r.unusedDays,
      charge: r.exitMonthCharge,
      credit: r.unusedDaysCredit,
      lines: s.exitLines.map(({ label, amount }) => ({ label, amount })),
    },
    oneTimeCharges: r.oneTimeCharges.map(({ label, amount }) => ({ label, amount })),
    oneTimeTotal: r.oneTimeTotal,
    futureInvoices: s.futureInvoices.map((i) => ({
      id: i.id,
      number: i.number,
      period: formatMonth(i.periodStart),
      total: i.total,
      amountPaid: i.amountPaid,
    })),
    roomAssets: s.roomAssets.map((a) => ({
      id: a.id,
      name: a.name,
      category: a.category,
      condition: a.condition,
      status: a.status,
      value: a.currentValue ?? a.purchaseCost,
    })),
    depositHeld: s.depositHeld,
    depositStatus: s.resident.deposit?.status ?? null,
    advance: s.advance,
    owed: r.owed,
    credits: r.credits,
    applied: r.applied,
    refundable: r.refundable,
    payable: r.payable,
    suggestedRefund: r.refundable,
    suggestedPayable: r.payable,
  }
}

/** Older callers passed one damage amount and one "other" amount. */
function normaliseDeductions(params: {
  deductions?: SettlementDeduction[]
  damageDeduction?: number
  otherCharges?: number
}): SettlementDeduction[] {
  const list = [...(params.deductions ?? [])]
  if (params.damageDeduction) list.push({ label: 'Damage', amount: params.damageDeduction })
  if (params.otherCharges) list.push({ label: 'Other charges', amount: params.otherCharges })
  return list
}

/** Computes the final settlement without writing anything. */
export async function previewCheckout(params: {
  residentId: string
  exitDate: Date
  deductions?: SettlementDeduction[]
  damageDeduction?: number
  otherCharges?: number
  assetDamages?: AssetDamage[]
}): Promise<CheckoutPreview> {
  const loaded = await loadSettlement(prisma, {
    residentId: params.residentId,
    exitDate: params.exitDate,
    deductions: normaliseDeductions(params),
    assetDamages: params.assetDamages,
  })
  return toPreview(loaded)
}

type OpenInvoiceRow = {
  id: string
  number: string
  status: InvoiceStatus
  subtotal: number
  total: number
  amountPaid: number
  balance: number
}

function nextStatus(row: OpenInvoiceRow): InvoiceStatus {
  if (row.balance <= 0) return 'PAID'
  if (row.status === 'OVERDUE') return 'OVERDUE'
  return row.amountPaid > 0 ? 'PARTIALLY_PAID' : row.status
}

export async function completeCheckout(params: {
  residentId: string
  exitDate: Date
  reason?: string
  deductions?: SettlementDeduction[]
  damageDeduction?: number
  otherCharges?: number
  settlementNote?: string
  /** Refund paid out now. Leave empty to pay it later ("Mark refund paid"). */
  refund?: RefundInput | null
  /** @deprecated use `refund`. */
  refundPaid?: boolean
  /** Room inspection and clearance checklists captured in the dialog. */
  inspection?: Checklist | null
  clearance?: Checklist | null
  /** Assets in the room found damaged or missing; each amount is a deduction. */
  assetDamages?: AssetDamage[]
  actor: { id?: string; name: string }
}) {
  const deductions = normaliseDeductions(params)
  const refundNow: RefundInput | null =
    params.refund ?? (params.refundPaid ? { method: 'CASH' } : null)

  const result = await retryOnUniqueConflict(
    () =>
      prisma.$transaction(
        async (tx) => {
          // Lock the resident's invoices and payments so a payment landing
          // mid-checkout cannot be counted twice or missed.
          await tx.$queryRaw`
            SELECT "id" FROM "RentInvoice" WHERE "residentId" = ${params.residentId} ORDER BY "id" FOR UPDATE
          `
          await tx.$queryRaw`
            SELECT "id" FROM "RentPayment" WHERE "residentId" = ${params.residentId} ORDER BY "id" FOR UPDATE
          `

          const resident = await tx.resident.findUnique({
            where: { id: params.residentId },
            include: {
              bed: { include: { room: true } },
              property: { include: { organization: { include: { settings: true } } } },
              deposit: true,
            },
          })
          if (!resident) throw new NotFoundError('Resident not found')
          if (resident.status === 'CHECKED_OUT') throw new ConflictError('Already checked out')
          if (resident.status === 'PENDING') {
            throw new ConflictError('This resident has not checked in yet')
          }

          const s = await loadSettlement(tx, {
            residentId: resident.id,
            exitDate: params.exitDate,
            deductions,
            assetDamages: params.assetDamages,
          })
          const r = s.result
          const exitDate = s.exitDate
          const ledgerBase = { organizationId: resident.organizationId, residentId: resident.id }

          // --- 0. Cancel invoices for months after the exit -----------------
          // Never left outstanding; what was paid on them is released and
          // counted as advance in the settlement (already in `s`).
          for (const inv of s.futureInvoices) {
            await tx.paymentAllocation.deleteMany({ where: { invoiceId: inv.id } })
            await tx.rentInvoice.update({
              where: { id: inv.id },
              data: {
                status: 'CANCELLED',
                amountPaid: 0,
                balance: 0,
                paidAt: null,
                notes: `Cancelled at checkout — resident left on ${formatDate(exitDate)}`,
              },
            })
            if (inv.status !== 'DRAFT' && inv.total > 0) {
              await appendLedger(tx, {
                ...ledgerBase,
                kind: 'ADJUSTMENT',
                label: `Invoice ${inv.number} cancelled — ${formatMonth(inv.periodStart)} is after the exit`,
                credit: inv.total,
                // Never before the charge it reverses, so running balances read right.
                entryDate: inv.issueDate > exitDate ? inv.issueDate : exitDate,
                refType: 'RentInvoice',
                refId: inv.id,
              })
            }
            await recordActivity(
              {
                organizationId: resident.organizationId,
                propertyId: resident.propertyId,
                actorId: params.actor.id,
                actorName: params.actor.name,
                event: 'INVOICE_ADJUSTED',
                entityType: 'RentInvoice',
                entityId: inv.id,
                summary: `${inv.number} (${formatMonth(inv.periodStart)}) cancelled at ${resident.fullName}'s checkout${
                  inv.amountPaid > 0 ? ` — ${formatMoney(inv.amountPaid)} paid on it moved to the settlement` : ''
                }`,
                meta: { action: 'CANCELLED_AT_CHECKOUT', residentId: resident.id },
                before: { status: inv.status, total: inv.total, amountPaid: inv.amountPaid },
                after: { status: 'CANCELLED', total: inv.total, amountPaid: 0, balance: 0 },
              },
              tx,
            )
          }
          if (s.futureInvoices.length) {
            // One-time charges billed on a cancelled invoice go on the settlement.
            await tx.residentCharge.updateMany({
              where: { residentId: resident.id, billedInvoiceId: { in: s.futureInvoices.map((i) => i.id) } },
              data: { billedInvoiceId: null },
            })
          }

          // Open invoices as a working set; the settlement invoice joins at the end.
          const open: OpenInvoiceRow[] = s.resident.invoices.map((i) => ({
            id: i.id,
            number: i.number,
            status: i.status,
            subtotal: i.subtotal,
            total: i.total,
            amountPaid: i.amountPaid,
            balance: i.balance,
          }))

          // --- 1. Final "Settlement" invoice -------------------------------
          const lines = [
            ...s.exitLines.map((l) => ({ kind: l.kind, label: l.label, amount: l.amount })),
            ...r.oneTimeCharges.map((c) => ({ kind: lineKindFor(c.category), label: c.label, amount: c.amount })),
            ...s.utilities.map((u) => ({
              kind: (u.kind === 'ELECTRICITY' || u.kind === 'WATER' ? u.kind : 'OTHER') as InvoiceLineKind,
              label: u.label,
              amount: u.amount,
            })),
            ...r.deductions.map((d) => ({
              kind: 'ADJUSTMENT' as InvoiceLineKind,
              label: `Deduction — ${d.label}`,
              amount: d.amount,
            })),
          ].filter((l) => l.amount !== 0)

          let settlementInvoice: { id: string; number: string } | null = null
          const settlementTotal = lines.reduce((sum, l) => sum + l.amount, 0)
          if (lines.length && settlementTotal > 0) {
            const number = await nextInvoiceNumber(
              tx,
              resident.organizationId,
              resident.property.organization.settings?.invoicePrefix ?? 'INV',
              exitDate,
            )
            const discount = -lines.filter((l) => l.amount < 0).reduce((sum, l) => sum + l.amount, 0)
            const subtotal = settlementTotal + discount
            // Monthly invoices sit at midnight on the 1st; the settlement is
            // stamped at the end of the exit day so (resident, period) stays unique.
            const stamp = new Date(exitDate)
            stamp.setHours(23, 59, 59, 0)
            const created = await tx.rentInvoice.create({
              data: {
                organizationId: resident.organizationId,
                propertyId: resident.propertyId,
                residentId: resident.id,
                number,
                periodStart: stamp,
                periodEnd: stamp,
                issueDate: exitDate,
                dueDate: exitDate,
                status: 'PENDING',
                subtotal,
                discount,
                total: settlementTotal,
                balance: settlementTotal,
                autoGenerated: false,
                notes: 'Settlement — final dues at checkout',
                lines: {
                  create: lines
                    .filter((l) => l.amount > 0)
                    .map((l) => ({
                      kind: l.kind,
                      label: l.label,
                      quantity: 1,
                      unitPrice: l.amount,
                      amount: l.amount,
                    }))
                    .concat(
                      lines
                        .filter((l) => l.amount < 0)
                        .map((l) => ({
                          kind: 'DISCOUNT' as InvoiceLineKind,
                          label: l.label,
                          quantity: 1,
                          unitPrice: l.amount,
                          amount: l.amount,
                        })),
                    ),
                },
              },
            })
            settlementInvoice = { id: created.id, number: created.number }
            open.push({
              id: created.id,
              number: created.number,
              status: 'PENDING',
              subtotal,
              total: settlementTotal,
              amountPaid: 0,
              balance: settlementTotal,
            })

            const nonDeduction = settlementTotal - r.deductionsTotal
            if (nonDeduction > 0) {
              await appendLedger(tx, {
                ...ledgerBase,
                kind: 'CHARGE',
                label: `Settlement invoice ${created.number} — final rent & utilities`,
                debit: nonDeduction,
                entryDate: exitDate,
                refType: 'RentInvoice',
                refId: created.id,
              })
            }
            for (const d of r.deductions) {
              await appendLedger(tx, {
                ...ledgerBase,
                kind: 'CHARGE',
                label: `Deduction at checkout — ${d.label}`,
                debit: d.amount,
                entryDate: exitDate,
                refType: 'RentInvoice',
                refId: created.id,
              })
            }
            if (s.utilities.length) {
              await tx.utilityCharge.updateMany({
                where: { id: { in: s.utilities.map((u) => u.id) } },
                data: { billed: true, notes: `Billed on ${created.number}` },
              })
            }
            // One-time charges bill exactly once: claim them for the settlement.
            if (s.oneTimeIds.length) {
              const claimed = await tx.residentCharge.updateMany({
                where: { id: { in: s.oneTimeIds }, billedInvoiceId: null, voidedAt: null },
                data: { billedInvoiceId: created.id, lastBilledFor: exitDate },
              })
              if (claimed.count !== s.oneTimeIds.length) {
                throw new ConflictError('Charges changed during checkout. Please try again.')
              }
            }
          }

          // --- 2. Apply credits: unused days, advance, then deposit ---------
          const save = async (row: OpenInvoiceRow) => {
            await tx.rentInvoice.update({
              where: { id: row.id },
              data: {
                subtotal: row.subtotal,
                total: row.total,
                amountPaid: row.amountPaid,
                balance: Math.max(0, row.balance),
                status: nextStatus(row),
                paidAt: row.balance <= 0 ? exitDate : null,
              },
            })
            row.status = nextStatus(row)
          }

          if (r.applied.unusedCredit > 0) {
            // Credit the exit-month invoice first, then the oldest dues.
            const order = [
              ...open.filter((i) => i.id === s.exitMonthInvoice?.id),
              ...open.filter((i) => i.id !== s.exitMonthInvoice?.id),
            ]
            let left = r.applied.unusedCredit
            for (const row of order) {
              if (left <= 0) break
              const amount = Math.min(left, row.balance)
              if (amount <= 0) continue
              left -= amount
              await tx.invoiceLine.create({
                data: {
                  invoiceId: row.id,
                  kind: 'DISCOUNT',
                  label: `Unused days credit — ${r.unusedDays} day${r.unusedDays === 1 ? '' : 's'} after ${formatDate(exitDate)}`,
                  quantity: 1,
                  unitPrice: -amount,
                  amount: -amount,
                },
              })
              row.subtotal -= amount
              row.total -= amount
              row.balance -= amount
              await save(row)
            }
          }
          if (r.unusedDaysCredit > 0) {
            await appendLedger(tx, {
              ...ledgerBase,
              kind: 'ADJUSTMENT',
              label: `Credit for ${r.unusedDays} unused day${r.unusedDays === 1 ? '' : 's'} in ${formatMonth(s.monthStart)}`,
              credit: r.unusedDaysCredit,
              entryDate: exitDate,
              refType: s.exitMonthInvoice ? 'RentInvoice' : undefined,
              refId: s.exitMonthInvoice?.id,
            })
          }

          const allocate = async (
            sources: { id: string; free: number }[],
            total: number,
            fallbackDirect: boolean,
          ) => {
            let left = total
            for (const row of open) {
              if (left <= 0) break
              while (row.balance > 0 && left > 0) {
                const source = sources.find((p) => p.free > 0)
                const amount = Math.min(left, row.balance, source ? source.free : fallbackDirect ? left : 0)
                if (amount <= 0) break
                if (source) {
                  await tx.paymentAllocation.upsert({
                    where: { paymentId_invoiceId: { paymentId: source.id, invoiceId: row.id } },
                    create: { paymentId: source.id, invoiceId: row.id, amount },
                    update: { amount: { increment: amount } },
                  })
                  source.free -= amount
                }
                left -= amount
                row.amountPaid += amount
                row.balance -= amount
              }
              await save(row)
            }
          }

          if (r.applied.advance > 0) await allocate(s.rentPayments, r.applied.advance, false)
          // Deposits collected without a receipt (older records) still count.
          if (r.applied.deposit > 0) await allocate(s.depositPayments, r.applied.deposit, true)

          if (s.depositHeld > 0) {
            await appendLedger(tx, {
              ...ledgerBase,
              kind: 'DEPOSIT',
              label:
                r.applied.deposit >= s.depositHeld
                  ? 'Security deposit adjusted in full against final dues'
                  : r.applied.deposit > 0
                    ? `Security deposit applied — ${formatMoney(r.applied.deposit)} against dues`
                    : 'Security deposit released for refund',
              credit: s.depositHeld,
              entryDate: exitDate,
              refType: 'SecurityDeposit',
              refId: resident.deposit?.id,
            })
          }

          // --- 3. Refund ----------------------------------------------------
          const refundPaidNow = r.refundable > 0 && Boolean(refundNow)
          if (refundPaidNow) {
            await appendLedger(tx, {
              ...ledgerBase,
              kind: 'REFUND',
              label: `Refund paid — ${refundNow!.method.replace('_', ' ').toLowerCase()}${
                refundNow!.reference ? ` (${refundNow!.reference})` : ''
              }`,
              debit: r.refundable,
              entryDate: refundNow!.paidAt ? startOfDay(refundNow!.paidAt) : exitDate,
              refType: 'SecurityDeposit',
              refId: resident.deposit?.id,
            })
          }

          if (resident.deposit) {
            const status: DepositStatus =
              s.depositHeld <= 0
                ? resident.deposit.status
                : r.refundable <= 0
                  ? 'FORFEITED'
                  : refundPaidNow
                    ? 'REFUNDED'
                    : r.applied.deposit > 0
                      ? 'PARTIALLY_REFUNDED'
                      : 'COLLECTED'
            await tx.securityDeposit.update({
              where: { id: resident.deposit.id },
              data: {
                deductions: resident.deposit.deductions + r.applied.deposit,
                refunded: resident.deposit.refunded + (refundPaidNow ? r.depositReturned : 0),
                status,
                refundedAt: refundPaidNow ? (refundNow!.paidAt ?? new Date()) : null,
                refundMethod: refundPaidNow ? refundNow!.method : null,
                refundReference: refundPaidNow ? refundNow!.reference || null : null,
                refundNote: refundPaidNow ? refundNow!.note || null : null,
                reason: params.settlementNote ?? resident.deposit.reason,
              },
            })
          }

          // Running balances depend on entry order; recompute them once.
          await rebuildLedger(tx, resident.id)

          // --- 4. Checkout record -------------------------------------------
          const foodPart = s.exitLines.filter((l) => l.kind === 'FOOD').reduce((sum, l) => sum + l.amount, 0)
          const checkout = await tx.checkout.create({
            data: {
              residentId: resident.id,
              exitDate,
              reason: params.reason,
              outstandingRent: s.resident.invoices.reduce((sum, i) => sum + i.balance, 0),
              proRataRent: r.exitMonthCharge - foodPart - r.unusedDaysCredit,
              foodCharges: foodPart,
              utilityCharges: s.utilities.reduce((sum, u) => sum + u.amount, 0),
              otherCharges: r.oneTimeTotal,
              damageDeduction: r.deductionsTotal,
              inspection: params.inspection ? (params.inspection as Prisma.InputJsonValue) : undefined,
              clearance: params.clearance ? (params.clearance as Prisma.InputJsonValue) : undefined,
              depositHeld: s.depositHeld,
              refundAmount: r.refundable,
              payableAmount: r.payable,
              settledAt: r.refundable > 0 ? (refundPaidNow ? new Date() : null) : r.payable > 0 ? null : new Date(),
              settlementNote: params.settlementNote,
              processedBy: params.actor.name,
            },
          })

          // --- 4b. Damaged / missing assets ---------------------------------
          for (const { asset, damage } of s.damagedAssets) {
            const data =
              damage.outcome === 'MISSING'
                ? { status: 'MISSING' }
                : { condition: 'DAMAGED' as const, status: 'UNDER_REPAIR' }
            await tx.asset.update({
              where: { id: asset.id },
              data: {
                ...data,
                notes: [asset.notes, `${damage.outcome === 'MISSING' ? 'Missing' : 'Damaged'} at ${resident.fullName}'s checkout on ${formatDate(exitDate)}${damage.note ? ` — ${damage.note}` : ''}`]
                  .filter(Boolean)
                  .join('\n')
                  .slice(0, 1000),
              },
            })
            await recordActivity(
              {
                organizationId: resident.organizationId,
                propertyId: resident.propertyId,
                actorId: params.actor.id,
                actorName: params.actor.name,
                event: 'ASSET_UPDATED',
                entityType: 'Asset',
                entityId: asset.id,
                summary: `${asset.name} ${damage.outcome === 'MISSING' ? 'missing' : 'damaged'} at ${resident.fullName}'s checkout${
                  damage.amount > 0 ? ` — ${formatMoney(damage.amount)} deducted` : ''
                }`,
                before: { status: asset.status, condition: asset.condition },
                after: { ...data, deduction: damage.amount },
              },
              tx,
            )
          }

          // --- 5. Release the bed, stop food, close the account -------------
          if (resident.bed) {
            await tx.bed.update({
              where: { id: resident.bed.id },
              data: { status: 'AVAILABLE', residentId: null, blockedReason: null },
            })
            await tx.bedAllocation.updateMany({
              where: { bedId: resident.bed.id, residentId: resident.id, toDate: null },
              data: { toDate: exitDate },
            })
          }
          await tx.foodSubscription.updateMany({
            where: { residentId: resident.id },
            data: { active: false, endDate: exitDate },
          })
          await tx.resident.update({
            where: { id: resident.id },
            data: { status: 'CHECKED_OUT', exitDate, roomId: null },
          })
          if (resident.userId) {
            await tx.user.update({ where: { id: resident.userId }, data: { status: 'ARCHIVED' } })
          }
          await tx.mealAttendance.deleteMany({
            where: { residentId: resident.id, meal: { date: { gt: exitDate } } },
          })

          const outcome =
            r.refundable > 0
              ? refundPaidNow
                ? `refund ${formatMoney(r.refundable)} paid`
                : `refund ${formatMoney(r.refundable)} pending`
              : r.payable > 0
                ? `${formatMoney(r.payable)} still payable`
                : 'fully settled'

          await recordActivity(
            {
              organizationId: resident.organizationId,
              propertyId: resident.propertyId,
              actorId: params.actor.id,
              actorName: params.actor.name,
              event: 'CHECKOUT_COMPLETED',
              entityType: 'Resident',
              entityId: resident.id,
              summary: `${resident.fullName} checked out of ${resident.property.name} — ${outcome}`,
              meta: {
                owed: r.owed,
                credits: r.credits,
                refund: r.refundable,
                payable: r.payable,
                depositHeld: s.depositHeld,
                advance: s.advance,
                unusedDaysCredit: r.unusedDaysCredit,
                exitMonthCharge: r.exitMonthCharge,
                oneTimeCharges: r.oneTimeCharges,
                deductions: r.deductions,
                cancelledInvoices: s.futureInvoices.map((i) => i.number),
                damagedAssets: s.damagedAssets.map((d) => ({ id: d.asset.id, outcome: d.damage.outcome, amount: d.damage.amount })),
                settlementInvoice: settlementInvoice?.number ?? null,
              },
            },
            tx,
          )
          if (refundPaidNow) {
            await recordActivity(
              {
                organizationId: resident.organizationId,
                propertyId: resident.propertyId,
                actorId: params.actor.id,
                actorName: params.actor.name,
                event: 'REFUND_ISSUED',
                entityType: 'Resident',
                entityId: resident.id,
                summary: `${formatMoney(r.refundable)} refunded to ${resident.fullName} (${refundNow!.method.replace('_', ' ').toLowerCase()})`,
              },
              tx,
            )
          }
          if (resident.bed) {
            await recordActivity(
              {
                organizationId: resident.organizationId,
                propertyId: resident.propertyId,
                actorId: params.actor.id,
                actorName: params.actor.name,
                event: 'BED_RELEASED',
                entityType: 'Bed',
                entityId: resident.bed.id,
                summary: `Bed ${resident.bed.label} in Room ${resident.bed.room.number} is now available`,
              },
              tx,
            )
          }
          await notifyOrgAdmins(
            resident.organizationId,
            {
              kind: 'SYSTEM',
              title: 'Resident checked out',
              body: `${resident.fullName} left ${resident.property.name}. ${
                r.refundable > 0
                  ? refundPaidNow
                    ? `Refund of ${formatMoney(r.refundable)} paid.`
                    : `Refund of ${formatMoney(r.refundable)} is still to be paid.`
                  : r.payable > 0
                    ? `${formatMoney(r.payable)} still payable.`
                    : 'Fully settled.'
              }`,
              link: `/app/residents/${resident.id}`,
            },
            tx,
          )

          return { resident, checkout, settlementInvoice, refundPaid: refundPaidNow, result: r }
        },
        { timeout: 30000 },
      ),
    ['number'],
  )

  const { resident, checkout } = result
  await sendWhatsApp({
    organizationId: resident.organizationId,
    toName: resident.fullName,
    toPhone: resident.whatsappPhone || resident.phone,
    template: 'checkout_settlement',
    body:
      `Hi ${resident.fullName.split(' ')[0]} 👋\n\n` +
      `Your checkout from ${resident.property.name} on ${formatDate(checkout.exitDate)} is complete.\n\n` +
      `Total dues: ${formatMoney(result.result.owed)}\n` +
      `Deposit & credits: ${formatMoney(result.result.credits)}\n` +
      (checkout.refundAmount > 0
        ? `Refund: ${formatMoney(checkout.refundAmount)}${result.refundPaid ? ' (paid)' : ' (we will pay this shortly)'}\n`
        : '') +
      (checkout.payableAmount > 0 ? `Balance payable: ${formatMoney(checkout.payableAmount)}\n` : '') +
      `\nThank you for staying with us.`,
    variables: [resident.fullName, formatMoney(checkout.refundAmount)],
    refType: 'Checkout',
    refId: checkout.id,
  }).catch(() => undefined)

  return result
}

/** Pays out a refund that was left pending at checkout. */
export async function markRefundPaid(params: {
  residentId: string
  method: string
  reference?: string
  paidAt?: Date
  note?: string
  actor: { id?: string; name: string }
}) {
  const paidAt = params.paidAt ?? new Date()
  const methodLabel = params.method.replace('_', ' ').toLowerCase()

  const result = await prisma.$transaction(async (tx) => {
    const resident = await tx.resident.findUnique({
      where: { id: params.residentId },
      include: { checkout: true, deposit: true, property: true },
    })
    if (!resident) throw new NotFoundError('Resident not found')
    const checkout = resident.checkout
    if (!checkout || checkout.refundAmount <= 0) {
      throw new ConflictError('There is no refund due for this resident')
    }
    // Claim the pending refund atomically so it can only be paid once.
    const claimed = await tx.checkout.updateMany({
      where: { id: checkout.id, settledAt: null },
      data: { settledAt: paidAt },
    })
    if (claimed.count !== 1) throw new ConflictError('This refund has already been marked as paid')

    await appendLedger(tx, {
      organizationId: resident.organizationId,
      residentId: resident.id,
      kind: 'REFUND',
      label: `Refund paid — ${methodLabel}${params.reference ? ` (${params.reference})` : ''}`,
      debit: checkout.refundAmount,
      entryDate: startOfDay(paidAt),
      refType: 'SecurityDeposit',
      refId: resident.deposit?.id,
    })
    await rebuildLedger(tx, resident.id)

    if (resident.deposit) {
      const returned = Math.max(
        0,
        resident.deposit.collected - resident.deposit.deductions - resident.deposit.refunded,
      )
      await tx.securityDeposit.update({
        where: { id: resident.deposit.id },
        data: {
          status: 'REFUNDED',
          refunded: resident.deposit.refunded + returned,
          refundedAt: paidAt,
          refundMethod: params.method,
          refundReference: params.reference || null,
          refundNote: params.note || null,
        },
      })
    }

    await recordActivity(
      {
        organizationId: resident.organizationId,
        propertyId: resident.propertyId,
        actorId: params.actor.id,
        actorName: params.actor.name,
        event: 'REFUND_ISSUED',
        entityType: 'Resident',
        entityId: resident.id,
        summary: `${formatMoney(checkout.refundAmount)} refunded to ${resident.fullName} (${methodLabel})`,
        meta: { amount: checkout.refundAmount, method: params.method, reference: params.reference ?? null },
      },
      tx,
    )
    return { resident, amount: checkout.refundAmount }
  })

  await sendWhatsApp({
    organizationId: result.resident.organizationId,
    toName: result.resident.fullName,
    toPhone: result.resident.whatsappPhone || result.resident.phone,
    template: 'checkout_settlement',
    body:
      `Hi ${result.resident.fullName.split(' ')[0]} 👋\n\n` +
      `We have paid your refund of ${formatMoney(result.amount)} from ${result.resident.property.name}` +
      `${params.reference ? ` (ref ${params.reference})` : ''}.\n\nThank you for staying with us.`,
    variables: [result.resident.fullName, formatMoney(result.amount)],
    refType: 'Resident',
    refId: result.resident.id,
  }).catch(() => undefined)

  return result
}

/** Records a security deposit that was not collected at check-in. */
export async function collectDeposit(params: {
  residentId: string
  amount?: number
  method: PaymentMethodKind
  reference?: string
  paidAt?: Date
  actor: { id?: string; name: string }
}) {
  return retryOnUniqueConflict(
    () =>
      prisma.$transaction(async (tx) => {
        const resident = await tx.resident.findUnique({
          where: { id: params.residentId },
          include: { deposit: true, organization: { include: { settings: true } } },
        })
        if (!resident) throw new NotFoundError('Resident not found')
        if (resident.status === 'CHECKED_OUT') {
          throw new ConflictError('This resident has already checked out')
        }
        const deposit =
          resident.deposit ??
          (await tx.securityDeposit.create({
            data: {
              organizationId: resident.organizationId,
              residentId: resident.id,
              amount: resident.depositAmount,
            },
          }))
        const due = Math.max(0, deposit.amount - deposit.collected)
        if (due <= 0) throw new ConflictError('The deposit has already been collected in full')
        const amount = params.amount && params.amount > 0 ? Math.min(params.amount, due) : due

        const paidAt = params.paidAt ?? new Date()
        const receiptNumber = await nextReceiptNumber(
          tx,
          resident.organizationId,
          resident.organization.settings?.receiptPrefix ?? 'RCP',
          paidAt,
        )
        const payment = await tx.rentPayment.create({
          data: {
            organizationId: resident.organizationId,
            propertyId: resident.propertyId,
            residentId: resident.id,
            receiptNumber,
            amount,
            method: params.method,
            // Held money, not rent: never allocated to invoices or counted as revenue.
            purpose: 'DEPOSIT',
            status: 'SUCCESS',
            paidAt,
            reference: params.reference,
            notes: 'Security deposit collected',
            recordedBy: params.actor.name,
          },
        })
        const collected = deposit.collected + amount
        await tx.securityDeposit.update({
          where: { id: deposit.id },
          data: {
            collected,
            status: collected >= deposit.amount ? 'COLLECTED' : 'PENDING',
            collectedAt: paidAt,
          },
        })
        // Memo line, as at check-in: a deposit is held, not a payment towards rent.
        await appendLedger(tx, {
          organizationId: resident.organizationId,
          residentId: resident.id,
          kind: 'DEPOSIT',
          label: `Security deposit received — ${formatMoney(amount)} (${receiptNumber})`,
          entryDate: paidAt,
          refType: 'SecurityDeposit',
          refId: deposit.id,
        })
        await recordActivity(
          {
            organizationId: resident.organizationId,
            propertyId: resident.propertyId,
            actorId: params.actor.id,
            actorName: params.actor.name,
            event: 'PAYMENT_COMPLETED',
            entityType: 'RentPayment',
            entityId: payment.id,
            summary: `Security deposit ${formatMoney(amount)} from ${resident.fullName} (${receiptNumber})`,
            meta: { residentId: resident.id, amount, purpose: 'DEPOSIT', method: params.method },
          },
          tx,
        )
        return { resident, payment, amount, remaining: deposit.amount - collected }
      }),
    ['receiptNumber'],
  )
}

/** Marks a resident as serving notice; the bed stays occupied until exit. */
export async function markNotice(params: {
  residentId: string
  noticeDate: Date
  exitDate: Date
  actor: { id?: string; name: string }
}) {
  const resident = await prisma.resident.update({
    where: { id: params.residentId },
    data: {
      status: 'NOTICE',
      noticeDate: startOfDay(params.noticeDate),
      exitDate: startOfDay(params.exitDate),
    },
    include: { property: true },
  })
  await recordActivity({
    organizationId: resident.organizationId,
    propertyId: resident.propertyId,
    actorId: params.actor.id,
    actorName: params.actor.name,
    event: 'RESIDENT_UPDATED',
    entityType: 'Resident',
    entityId: resident.id,
    summary: `${resident.fullName} gave notice — expected exit ${formatDate(params.exitDate)}`,
  })
  return resident
}

/** Beds that free up within the next N days, for the ops panel. */
export async function upcomingVacancies(propertyIds: string[], days = 30) {
  return prisma.resident.findMany({
    where: {
      propertyId: { in: propertyIds },
      status: 'NOTICE',
      exitDate: { lte: addDays(new Date(), days) },
    },
    include: { bed: { include: { room: true } }, property: true },
    orderBy: { exitDate: 'asc' },
  })
}

/** Aggregate used across dashboards: occupancy for a set of properties. */
export async function occupancyFor(propertyIds: string[]) {
  const rows = await prisma.bed.groupBy({
    by: ['status'],
    where: { propertyId: { in: propertyIds } },
    _count: { _all: true },
  })
  const get = (s: string) => rows.find((r) => r.status === s)?._count._all ?? 0
  const occupied = get('OCCUPIED')
  const available = get('AVAILABLE')
  const reserved = get('RESERVED')
  const maintenance = get('MAINTENANCE')
  const blocked = get('BLOCKED')
  const total = occupied + available + reserved + maintenance + blocked
  return {
    total,
    occupied,
    available,
    reserved,
    maintenance,
    blocked,
    rate: total ? Math.round((occupied / total) * 100) : 0,
  }
}

/** Writes today's occupancy snapshot for every property (used by trends). */
export async function snapshotOccupancy(propertyIds?: string[]) {
  const properties = await prisma.property.findMany({
    where: { archivedAt: null, ...(propertyIds ? { id: { in: propertyIds } } : {}) },
    select: { id: true },
  })
  const date = startOfDay(new Date())
  for (const property of properties) {
    const stats = await occupancyFor([property.id])
    await prisma.occupancySnapshot.upsert({
      where: { propertyId_date: { propertyId: property.id, date } },
      create: {
        propertyId: property.id,
        date,
        totalBeds: stats.total,
        occupied: stats.occupied,
        vacant: stats.available,
        reserved: stats.reserved,
        maintenance: stats.maintenance,
      },
      update: {
        totalBeds: stats.total,
        occupied: stats.occupied,
        vacant: stats.available,
        reserved: stats.reserved,
        maintenance: stats.maintenance,
      },
    })
  }
  return { snapshots: properties.length, date }
}

/** Residents whose deposit is still uncollected — an ops nudge. */
export async function pendingDeposits(organizationId: string, propertyIds: string[]) {
  return prisma.securityDeposit.findMany({
    where: {
      organizationId,
      status: 'PENDING',
      resident: { propertyId: { in: propertyIds }, status: { in: ['ACTIVE', 'NOTICE'] } },
    },
    include: { resident: { include: { property: true } } },
    orderBy: { createdAt: 'desc' },
    take: 20,
  })
}

export async function endOfMonthUtilitySplit(params: {
  propertyId: string
  month: Date
  totalAmount: number
  kind: string
  actor: { id?: string; name: string }
}) {
  const periodStart = startOfMonth(params.month)
  // Date-only column: IST midnight of the month's last day.
  const periodEnd = startOfDay(endOfMonth(params.month))
  const residents = await prisma.resident.findMany({
    where: { propertyId: params.propertyId, status: { in: ['ACTIVE', 'NOTICE'] } },
    select: { id: true, organizationId: true },
  })
  if (!residents.length) throw new ValidationError('No active residents to split this bill across')

  const share = Math.round(params.totalAmount / residents.length)
  await prisma.utilityCharge.createMany({
    data: residents.map((r) => ({
      organizationId: r.organizationId,
      propertyId: params.propertyId,
      residentId: r.id,
      kind: params.kind,
      periodStart,
      periodEnd,
      amount: share,
    })),
  })
  return { residents: residents.length, share }
}
