import { NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { fail, route } from '@/lib/api-helpers'
import { assertResidentAccess, requirePermission } from '@/lib/tenancy'
import { formatDate, formatMonth } from '@/lib/utils'
import { renderDocument, rs } from '@/server/documents/pdf'

/**
 * GET /api/documents/rent-invoice/<id>.pdf
 * GET /api/documents/rent-receipt/<id>.pdf
 *
 * Owners/managers download for residents in their PGs; a resident downloads
 * only their own. Access goes through assertResidentAccess, so a guessed id
 * from another PG or organization is refused.
 */
export const GET = route(
  async ({ user, request }) => {
    const parts = new URL(request.url).pathname.split('/')
    const id = parts[parts.length - 1].replace(/\.pdf$/, '')
    const kind = parts[parts.length - 2]
    // Residents download their own (checked below); staff need rent.view.
    if (user.role !== 'TENANT') requirePermission(user, 'rent.view')

    if (kind === 'rent-invoice') {
      const invoice = await prisma.rentInvoice.findUnique({
        where: { id },
        include: {
          lines: true,
          resident: { select: { id: true, fullName: true, code: true, phone: true, room: { select: { number: true } } } },
          property: { select: { name: true, addressLine: true, city: true } },
          organization: { select: { name: true, contactPhone: true, contactEmail: true, gstin: true } },
        },
      })
      if (!invoice) return fail('Invoice not found', 404)
      await assertResidentAccess(user, invoice.resident.id)

      const pdf = await renderDocument({
        title: 'Rent invoice',
        reference: invoice.number,
        issuer: {
          name: invoice.property.name,
          lines: [
            `${invoice.property.addressLine}, ${invoice.property.city}`,
            `${invoice.organization.name} · ${invoice.organization.contactPhone}`,
            ...(invoice.organization.gstin ? [`GSTIN ${invoice.organization.gstin}`] : []),
          ],
        },
        billTo: {
          label: 'Billed to',
          name: invoice.resident.fullName,
          lines: [`Resident ${invoice.resident.code}`, invoice.resident.phone, ...(invoice.resident.room ? [`Room ${invoice.resident.room.number}`] : [])],
        },
        meta: [
          ['Period', formatMonth(invoice.periodStart)],
          ['Issued', formatDate(invoice.issueDate)],
          ['Due', formatDate(invoice.dueDate)],
          ['Status', invoice.status.replace('_', ' ')],
        ],
        items: invoice.lines.map((l) => ({ label: l.label, qty: l.quantity, amount: l.amount })),
        totals: [
          ['Total', rs(invoice.total)],
          ['Paid', rs(invoice.amountPaid)],
          ['Balance due', rs(invoice.balance), true],
        ],
        stamp: invoice.balance === 0 && invoice.status === 'PAID' ? { text: 'PAID', tone: 'paid' } : invoice.status === 'OVERDUE' ? { text: 'OVERDUE', tone: 'due' } : undefined,
        notes: invoice.balance > 0 ? ['Please pay by the due date to avoid a late fee. You can pay from the StayFlow app.'] : [],
        footer: `Generated by StayFlow on ${formatDate(new Date())}. This is a computer-generated document and needs no signature.`,
      })
      return pdfResponse(pdf, `${invoice.number}.pdf`)
    }

    if (kind === 'rent-receipt') {
      const payment = await prisma.rentPayment.findUnique({
        where: { id },
        include: {
          allocations: { include: { invoice: { select: { number: true, periodStart: true } } } },
          resident: { select: { id: true, fullName: true, code: true, phone: true } },
          property: { select: { name: true, addressLine: true, city: true } },
          organization: { select: { name: true, contactPhone: true, gstin: true } },
        },
      })
      if (!payment) return fail('Receipt not found', 404)
      await assertResidentAccess(user, payment.resident.id)

      const allocated = payment.allocations.reduce((s, a) => s + a.amount, 0)
      const items =
        payment.status === 'REVERSED'
          ? [{ label: 'Payment reversed — not applied to any invoice', amount: payment.amount }]
          : payment.purpose === 'DEPOSIT'
          ? [{ label: 'Security deposit (refundable)', amount: payment.amount }]
          : [
              ...payment.allocations.map((a) => ({
                label: `Rent ${formatMonth(a.invoice.periodStart)} (${a.invoice.number})`,
                amount: a.amount,
              })),
              ...(payment.amount - payment.refundedAmount > allocated ? [{ label: 'Advance (adjusted against the next invoice)', amount: payment.amount - payment.refundedAmount - allocated }] : []),
              ...(payment.refundedAmount > 0 ? [{ label: 'Refunded', amount: payment.refundedAmount }] : []),
            ]

      const pdf = await renderDocument({
        title: 'Payment receipt',
        reference: payment.receiptNumber,
        issuer: {
          name: payment.property.name,
          lines: [
            `${payment.property.addressLine}, ${payment.property.city}`,
            `${payment.organization.name} · ${payment.organization.contactPhone}`,
            ...(payment.organization.gstin ? [`GSTIN ${payment.organization.gstin}`] : []),
          ],
        },
        billTo: {
          label: 'Received from',
          name: payment.resident.fullName,
          lines: [`Resident ${payment.resident.code}`, payment.resident.phone],
        },
        meta: [
          ['Date', formatDate(payment.paidAt)],
          ['Method', payment.method.replace('_', ' ')],
          ...(payment.reference ? ([['Reference', payment.reference]] as [string, string][]) : []),
          ...(payment.utr ? ([['UTR', payment.utr]] as [string, string][]) : []),
          ...(payment.gatewayPaymentId ? ([['Gateway ID', payment.gatewayPaymentId]] as [string, string][]) : []),
        ],
        items,
        totals: [['Amount received', rs(payment.amount), true]],
        stamp:
          payment.status === 'REVERSED'
            ? { text: 'REVERSED', tone: 'due' }
            : payment.isDemo
              ? { text: 'DEMO - NO MONEY MOVED', tone: 'demo' }
              : payment.status === 'REFUNDED'
                ? { text: 'REFUNDED', tone: 'due' }
                : payment.status === 'SUCCESS'
                  ? { text: 'RECEIVED', tone: 'paid' }
                  : undefined,
        ...(payment.status === 'REVERSED' || payment.refundedAmount > 0
          ? {
              notes: [
                ...(payment.status === 'REVERSED'
                  ? [`This payment was reversed on ${formatDate(payment.reversedAt ?? new Date())}${payment.reversalReason ? ` — ${payment.reversalReason}` : ''}. It does not count towards any invoice.`]
                  : []),
                ...(payment.refundedAmount > 0 ? [`Rs ${payment.refundedAmount.toLocaleString('en-IN')} of this payment was refunded.`] : []),
              ],
            }
          : {}),
        footer: `Generated by StayFlow on ${formatDate(new Date())}. This is a computer-generated receipt and needs no signature.`,
      })
      return pdfResponse(pdf, `${payment.receiptNumber}.pdf`)
    }

    return fail('Unknown document', 404)
  },
  { roles: ['OWNER', 'MANAGER', 'WORKER', 'TENANT', 'SUPER_ADMIN'] },
)

function pdfResponse(bytes: Uint8Array, filename: string) {
  return new NextResponse(Buffer.from(bytes), {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `inline; filename="${filename}"`,
      'Cache-Control': 'private, no-store',
    },
  })
}
