import { NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { fail, route } from '@/lib/api-helpers'
import { assertResidentAccess, requirePermission } from '@/lib/tenancy'
import { formatDate, formatMonth } from '@/lib/utils'
import { renderDocument, rs } from '@/server/documents/pdf'
import { openItems, readChecklist } from '@/lib/checkout-checklist'
import { recordActivity } from '@/server/events'
import type { SessionUser } from '@/lib/auth'

/**
 * Platform staff can open any customer's resident documents (for support), so
 * every such download leaves an ADMIN_ACTION row in that customer's log.
 */
async function auditAdminDownload(user: SessionUser, residentId: string, what: string) {
  if (user.role !== 'SUPER_ADMIN') return
  const resident = await prisma.resident.findUnique({
    where: { id: residentId },
    select: { organizationId: true, propertyId: true, fullName: true },
  })
  if (!resident) return
  await recordActivity({
    organizationId: resident.organizationId,
    propertyId: resident.propertyId,
    actorId: user.id,
    actorName: user.name,
    actorRole: user.role,
    event: 'ADMIN_ACTION',
    entityType: 'Resident',
    entityId: residentId,
    summary: `StayFlow support downloaded ${what} for ${resident.fullName}`,
    meta: { action: 'DOCUMENT_DOWNLOAD', document: what },
  })
}

/**
 * GET /api/documents/rent-invoice/<id>.pdf
 * GET /api/documents/rent-receipt/<id>.pdf
 * GET /api/documents/checkout-settlement/<residentId>.pdf
 *
 * Owners/managers download for residents in their PGs; a resident downloads
 * only their own. Access goes through assertResidentAccess, so a guessed id
 * from another PG or organization is refused.
 */
export const GET = route(
  async ({ user, request }) => {
    const parts = new URL(request.url).pathname.split('/')
    const id = parts[parts.length - 1].replace(/\.pdf$/, '')
    const kind = parts[parts.length - 2]
    // Residents download their own (checked below); staff need rent.view.
    if (user.role !== 'TENANT') requirePermission(user, 'rent.view')

    if (kind === 'rent-invoice') {
      const invoice = await prisma.rentInvoice.findUnique({
        where: { id },
        include: {
          lines: true,
          resident: { select: { id: true, fullName: true, code: true, phone: true, room: { select: { number: true } } } },
          property: { select: { name: true, addressLine: true, city: true } },
          organization: { select: { name: true, contactPhone: true, contactEmail: true, gstin: true } },
        },
      })
      if (!invoice) return fail('Invoice not found', 404)
      await assertResidentAccess(user, invoice.resident.id)
      await auditAdminDownload(user, invoice.resident.id, `rent invoice ${invoice.number}`)

      const pdf = await renderDocument({
        title: 'Rent invoice',
        reference: invoice.number,
        issuer: {
          name: invoice.property.name,
          lines: [
            `${invoice.property.addressLine}, ${invoice.property.city}`,
            `${invoice.organization.name} · ${invoice.organization.contactPhone}`,
            ...(invoice.organization.gstin ? [`GSTIN ${invoice.organization.gstin}`] : []),
          ],
        },
        billTo: {
          label: 'Billed to',
          name: invoice.resident.fullName,
          lines: [`Resident ${invoice.resident.code}`, invoice.resident.phone, ...(invoice.resident.room ? [`Room ${invoice.resident.room.number}`] : [])],
        },
        meta: [
          ['Period', formatMonth(invoice.periodStart)],
          ['Issued', formatDate(invoice.issueDate)],
          ['Due', formatDate(invoice.dueDate)],
          ['Status', invoice.status.replace('_', ' ')],
        ],
        items: invoice.lines.map((l) => ({ label: l.label, qty: l.quantity, amount: l.amount })),
        totals: [
          ['Total', rs(invoice.total)],
          ['Paid', rs(invoice.amountPaid)],
          ['Balance due', rs(invoice.balance), true],
        ],
        stamp: invoice.balance === 0 && invoice.status === 'PAID' ? { text: 'PAID', tone: 'paid' } : invoice.status === 'OVERDUE' ? { text: 'OVERDUE', tone: 'due' } : undefined,
        notes: invoice.balance > 0 ? ['Please pay by the due date to avoid a late fee. You can pay from the StayFlow app.'] : [],
        footer: `Generated by StayFlow on ${formatDate(new Date())}. This is a computer-generated document and needs no signature.`,
      })
      return pdfResponse(pdf, `${invoice.number}.pdf`)
    }

    if (kind === 'rent-receipt') {
      const payment = await prisma.rentPayment.findUnique({
        where: { id },
        include: {
          allocations: { include: { invoice: { select: { number: true, periodStart: true } } } },
          resident: { select: { id: true, fullName: true, code: true, phone: true } },
          property: { select: { name: true, addressLine: true, city: true } },
          organization: { select: { name: true, contactPhone: true, gstin: true } },
        },
      })
      if (!payment) return fail('Receipt not found', 404)
      await assertResidentAccess(user, payment.resident.id)
      await auditAdminDownload(user, payment.resident.id, `receipt ${payment.receiptNumber}`)

      const allocated = payment.allocations.reduce((s, a) => s + a.amount, 0)
      const items =
        payment.status === 'REVERSED'
          ? [{ label: 'Payment reversed — not applied to any invoice', amount: payment.amount }]
          : payment.purpose === 'DEPOSIT'
          ? [{ label: 'Security deposit (refundable)', amount: payment.amount }]
          : [
              ...payment.allocations.map((a) => ({
                label: `Rent ${formatMonth(a.invoice.periodStart)} (${a.invoice.number})`,
                amount: a.amount,
              })),
              ...(payment.amount - payment.refundedAmount > allocated ? [{ label: 'Advance (adjusted against the next invoice)', amount: payment.amount - payment.refundedAmount - allocated }] : []),
              ...(payment.refundedAmount > 0 ? [{ label: 'Refunded', amount: payment.refundedAmount }] : []),
            ]

      const pdf = await renderDocument({
        title: 'Payment receipt',
        reference: payment.receiptNumber,
        issuer: {
          name: payment.property.name,
          lines: [
            `${payment.property.addressLine}, ${payment.property.city}`,
            `${payment.organization.name} · ${payment.organization.contactPhone}`,
            ...(payment.organization.gstin ? [`GSTIN ${payment.organization.gstin}`] : []),
          ],
        },
        billTo: {
          label: 'Received from',
          name: payment.resident.fullName,
          lines: [`Resident ${payment.resident.code}`, payment.resident.phone],
        },
        meta: [
          ['Date', formatDate(payment.paidAt)],
          ['Method', payment.method.replace('_', ' ')],
          ...(payment.reference ? ([['Reference', payment.reference]] as [string, string][]) : []),
          ...(payment.utr ? ([['UTR', payment.utr]] as [string, string][]) : []),
          ...(payment.gatewayPaymentId ? ([['Gateway ID', payment.gatewayPaymentId]] as [string, string][]) : []),
        ],
        items,
        totals: [['Amount received', rs(payment.amount), true]],
        stamp:
          payment.status === 'REVERSED'
            ? { text: 'REVERSED', tone: 'due' }
            : payment.isDemo
              ? { text: 'DEMO - NO MONEY MOVED', tone: 'demo' }
              : payment.status === 'REFUNDED'
                ? { text: 'REFUNDED', tone: 'due' }
                : payment.status === 'SUCCESS'
                  ? { text: 'RECEIVED', tone: 'paid' }
                  : undefined,
        ...(payment.status === 'REVERSED' || payment.refundedAmount > 0
          ? {
              notes: [
                ...(payment.status === 'REVERSED'
                  ? [`This payment was reversed on ${formatDate(payment.reversedAt ?? new Date())}${payment.reversalReason ? ` — ${payment.reversalReason}` : ''}. It does not count towards any invoice.`]
                  : []),
                ...(payment.refundedAmount > 0 ? [`Rs ${payment.refundedAmount.toLocaleString('en-IN')} of this payment was refunded.`] : []),
              ],
            }
          : {}),
        footer: `Generated by StayFlow on ${formatDate(new Date())}. This is a computer-generated receipt and needs no signature.`,
      })
      return pdfResponse(pdf, `${payment.receiptNumber}.pdf`)
    }

    if (kind === 'checkout-settlement') {
      await assertResidentAccess(user, id)
      await auditAdminDownload(user, id, 'the checkout settlement')
      const resident = await prisma.resident.findUnique({
        where: { id },
        include: {
          checkout: true,
          property: { select: { name: true, addressLine: true, city: true } },
          organization: { select: { name: true, contactPhone: true, gstin: true } },
          allocations: { orderBy: { fromDate: 'desc' }, take: 1, include: { bed: { include: { room: { select: { number: true } } } } } },
        },
      })
      const checkout = resident?.checkout
      if (!resident || !checkout) return fail('No settlement for this resident', 404)

      const [settlement, completed] = await Promise.all([
        prisma.rentInvoice.findFirst({
          where: { residentId: resident.id, notes: 'Settlement — final dues at checkout' },
          include: { lines: true },
          orderBy: { createdAt: 'desc' },
        }),
        prisma.activityLog.findFirst({
          where: { entityType: 'Resident', entityId: resident.id, event: 'CHECKOUT_COMPLETED' },
          orderBy: { createdAt: 'desc' },
          select: { meta: true },
        }),
      ])
      const meta = (completed?.meta ?? {}) as { owed?: number; credits?: number; advance?: number; unusedDaysCredit?: number; cancelledInvoices?: string[] }

      const items: { label: string; amount: number }[] = []
      if (checkout.outstandingRent > 0) items.push({ label: 'Unpaid rent invoices at exit', amount: checkout.outstandingRent })
      if (settlement) {
        for (const l of settlement.lines) items.push({ label: l.label, amount: l.amount })
      } else {
        if (checkout.proRataRent + checkout.foodCharges > 0) items.push({ label: 'Exit month charges', amount: checkout.proRataRent + checkout.foodCharges })
        if (checkout.utilityCharges > 0) items.push({ label: 'Utilities', amount: checkout.utilityCharges })
        if (checkout.otherCharges > 0) items.push({ label: 'Other charges', amount: checkout.otherCharges })
        if (checkout.damageDeduction > 0) items.push({ label: 'Deductions', amount: checkout.damageDeduction })
      }
      if (meta.unusedDaysCredit) items.push({ label: 'Credit for unused days (already invoiced)', amount: -meta.unusedDaysCredit })
      if (meta.advance) items.push({ label: 'Advance paid (unused)', amount: -meta.advance })
      if (checkout.depositHeld > 0) items.push({ label: 'Security deposit held', amount: -checkout.depositHeld })

      const bed = resident.allocations[0]?.bed
      const inspection = readChecklist(checkout.inspection)
      const clearance = readChecklist(checkout.clearance)
      const notes = [
        ...(meta.cancelledInvoices?.length ? [`Cancelled (after exit): ${meta.cancelledInvoices.join(', ')}`] : []),
        ...(inspection ? [`Room inspection: ${inspection.items.filter((i) => i.ok).length}/${inspection.items.length} items OK`] : []),
        ...openItems(inspection).map((i) => `  - ${i.label}${i.note ? `: ${i.note}` : ''}`),
        ...(clearance ? [`Clearance: ${clearance.items.filter((i) => i.ok).length}/${clearance.items.length} done`] : []),
        ...openItems(clearance).map((i) => `  - Pending: ${i.label}`),
        ...(checkout.settlementNote ? [`Note: ${checkout.settlementNote}`] : []),
        checkout.lockedAt
          ? `Settlement closed on ${formatDate(checkout.lockedAt)}. Any later correction is issued as a credit or debit note.`
          : 'Settlement open — it may still be updated before it is closed.',
      ]

      const pdf = await renderDocument({
        title: 'Final settlement',
        reference: resident.code,
        issuer: {
          name: resident.property.name,
          lines: [
            `${resident.property.addressLine}, ${resident.property.city}`,
            `${resident.organization.name} · ${resident.organization.contactPhone}`,
            ...(resident.organization.gstin ? [`GSTIN ${resident.organization.gstin}`] : []),
          ],
        },
        billTo: {
          label: 'Resident',
          name: resident.fullName,
          lines: [`Resident ${resident.code}`, resident.phone, ...(bed ? [`Room ${bed.room.number} · Bed ${bed.label}`] : [])],
        },
        meta: [
          ['Joined', formatDate(resident.joiningDate)],
          ['Exit date', formatDate(checkout.exitDate)],
          ...(settlement ? ([['Invoice', settlement.number]] as [string, string][]) : []),
          ['Status', checkout.lockedAt ? 'Closed' : 'Open'],
        ],
        items,
        totals: [
          ...(meta.owed != null ? ([['Total dues', rs(meta.owed)]] as [string, string][]) : []),
          ...(meta.credits != null ? ([['Deposit & credits', rs(meta.credits)]] as [string, string][]) : []),
          checkout.refundAmount > 0
            ? [checkout.settledAt ? 'Refunded' : 'Refund due to resident', rs(checkout.refundAmount), true]
            : checkout.payableAmount > 0
              ? ['Balance payable', rs(checkout.payableAmount), true]
              : ['Fully settled', rs(0), true],
        ],
        stamp: checkout.lockedAt
          ? { text: 'CLOSED', tone: 'paid' }
          : checkout.refundAmount > 0 && !checkout.settledAt
            ? { text: 'REFUND PENDING', tone: 'due' }
            : undefined,
        notes,
        footer: `Generated by StayFlow on ${formatDate(new Date())}. Processed by ${checkout.processedBy ?? 'the PG'}. Computer-generated; needs no signature.`,
      })
      return pdfResponse(pdf, `settlement-${resident.code}.pdf`)
    }

    return fail('Unknown document', 404)
  },
  { roles: ['OWNER', 'MANAGER', 'WORKER', 'TENANT', 'SUPER_ADMIN'] },
)

function pdfResponse(bytes: Uint8Array, filename: string) {
  return new NextResponse(Buffer.from(bytes), {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `inline; filename="${filename}"`,
      'Cache-Control': 'private, no-store',
    },
  })
}
